name: Update gist
on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: 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
          GIST_ID: daa219a7ef3e97eb11e460697902e9d1
          TIMEZONE: Asia/Seoul
